Write Python code to remove outliers from any given DataFrame

[https://www.storytellingwithdata.com/blog/what-is-a-boxplot](https://www.storytellingwithdata.com/blog/what-is-a-boxplot)

In [2]:
import pandas as pd
import numpy as np

data = {
    "name": ['William', 'Emma', 'Sofia', 'Markus', 'Edward', 'Thomas', 'Ethan', np.nan, 'Arun', 'Anika', 'Paulo'],
    "region": [np.nan, 'North', 'East', np.nan, 'West', 'West', 'South', np.nan, 'West', 'East', 'South'],
    "sales": [50000, 52000, np.nan, np.nan, 42000, 72000, 49000, np.nan, 67000, 65000, 67000],
    "expenses": [42000, 43000, np.nan, np.nan, 38000, 39000, 42000, np.nan, 39000, 50000, 45000],
}

df = pd.DataFrame(data)
df

# Dropping outliers

# I had to pass numeric_only=True parameter as I have
# newer version of pandas, you may or may not need 
# to pass this parameter.

# You can write df.quantile(0.25), in exams.

# The basic idea is to calculate the first and third quartile,
# A quartile is something that divides the whole dataset into 4 equal parts.
# We then apply `1.5 * IQR` rule to detect the outliers.
# IQR is the difference between the first and third quartile.
# The outliers are the values that are less than `q1 - 1.5 * IQR`
# We give a leeway of 1.5 times the IQR to detect the outliers.
# They are outliers cause even after giving a leeway of 1.5 times the IQR,
# they are still far away from the first and third quartile, creating an imbalance in 
# our data.

def remove_outliers(df, col):
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    return df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]
df_no_outliers = remove_outliers(df, 'sales')
print(df_no_outliers.shape)
df_no_outliers

(8, 4)

       name region    sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

30. Consider the following data:

```python
data = {
 "A": ["TeamA", "TeamB", "TeamB", "TeamC", "TeamA"],
 "B": [50, 40, 40, 30, 50],
 "C": [True, False, False, False, True]
}
```

Convert this to a Pandas DataFrame and remove duplicate rows from it. Reset index values

In [7]:
data = {
 "A": ["TeamA", "TeamB", "TeamB", "TeamC", "TeamA"],
 "B": [50, 40, 40, 30, 50],
 "C": [True, False, False, False, True]
}
df = pd.DataFrame(data)
df

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
2  TeamB  40  False
3  TeamC  30  False
4  TeamA  50   True

In [8]:
df.drop_duplicates(inplace=True)
df.reset_index()
df

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
3  TeamC  30  False

31. Consider the following autompg dataset:
https://raw.githubusercontent.com/Jovita7/Data-Analysis-and-Visualization/main/auto-mpg.csv
Write Python code to convert it to a DataFrame and remove mpg and cylinders columns from it

In [13]:
df = pd.read_csv("https://raw.githubusercontent.com/Jovita7/Data-Analysis-and-Visualization/main/auto-mpg.csv")
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [14]:
df.drop(['mpg', 'cylinders'], axis=1,inplace=True) # [Pass column names in list], axis = 1 means delete column, if you specify
# 0 it will search for rows named mpg, cylinders
df

,displacement,horsepower,weight,acceleration,model year,origin,car name
0,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,350.0,165,3693,11.5,70,1,buick skylark 320
2,318.0,150,3436,11.0,70,1,plymouth satellite
3,304.0,150,3433,12.0,70,1,amc rebel sst
4,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...
393,140.0,86,2790,15.6,82,1,ford mustang gl
394,97.0,52,2130,24.6,82,2,vw pickup
395,135.0,84,2295,11.6,82,1,dodge rampage
396,120.0,79,2625,18.6,82,1,ford ranger
397,119.0,82,2720,19.4,82,1,chevy s-10

32 Use the file heights_weights.csv (https://raw.githubusercontent.com/Jovita7/Data-Analysis-and-Visualization/main/heights_weights.csv)
which contains 10000 non-null values for heights and weights. The Male column shows 1 if the person is a Male and 0 if the person is a Female
.
1. Convert this file into a pandas Data Frame. (0.5 marks)
2. Display basic information like memory and data types for this data frame. (0.5 marks)
3. Display basic statistics like mean, std, quartiles, etc. for this data frame. (0.5 marks)
4. Create a correlation table for the data frame and comment about what kind of correlation is there between Height and Weight.(0.5
marks)
5. Do Height and Weightn any outliers? (1 mark)1 mark)tliers? (1 mark)

In [16]:
df = pd.read_csv("https://raw.githubusercontent.com/Jovita7/Data-Analysis-and-Visualization/main/heights_weights.csv")
df.info() # memory and data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Height  10000 non-null  float64
 1   Weight  10000 non-null  float64
 2   Male    10000 non-null  int64
dtypes: float64(2), int64(1)
memory usage: 234.5 KB

In [17]:
df.describe() # basic statistics

             Height        Weight          Male
count  10000.000000  10000.000000  10000.000000
mean      66.367560    161.440357      0.500000
std        3.847528     32.108439      0.500025
min       54.263133     64.700127      0.000000
25%       63.505620    135.818051      0.000000
50%       66.318070    161.212928      0.500000
75%       69.174262    187.169525      1.000000
max       78.998742    269.989699      1.000000

In [19]:
df.corr() # Corr table 
# Height and weight are positively correlated with corr efficient > 0.9

          Height    Weight      Male
Height  1.000000  0.924756  0.691072
Weight  0.924756  1.000000  0.796723
Male    0.691072  0.796723  1.000000

In [37]:
q1 = df.quantile(0.25)
q3 = df.quantile(0.75)
iqr = q3 - q1
lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr
outliers = df[(df < lower) | (df > upper)]
outliers.count() # Will give outlier count for all columns

Height    8
Weight    1
Male      0
dtype: int64

33 Use the file ipl-matches.csv which contains data of all the IPL matches from year 2008 to 2022. Read this csv file and display the basic
information like memory and data types for this data frame. Write python code for the following cases:
1. List out all matches gone in superover.
2. How Many Matches won by Chennai Super Kings at Kolkata.
3. In How Many Matches MS Dhoni is Player of Match Vs Mumbai Indians.
4. Display list of all matches in which Gujarat Titans won the Toss and Elected to Bat and won the match.
5. Display list of all matches won by Gujarat Titans

In [38]:
df = pd.read_csv("https://raw.githubusercontent.com/kevalsy/python-2/main/ipl-matches.csv")
df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [40]:
df[df['SuperOver']=='Y'] # ALl superovers

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
114,1254077,Chennai,2021-04-25,2021,20,Delhi Capitals,Sunrisers Hyderabad,"MA Chidambaram Stadium, Chepauk, Chennai",Delhi Capitals,bat,Y,Delhi Capitals,SuperOver,NaN,NaN,PP Shaw,"['PP Shaw', 'S Dhawan', 'RR Pant', 'SPD Smith'...","['DA Warner', 'JM Bairstow', 'KS Williamson', ...",CB Gaffaney,KN Ananthapadmanabhan
158,1216512,Abu Dhabi,2020-10-18,2020/21,35,Kolkata Knight Riders,Sunrisers Hyderabad,Sheikh Zayed Stadium,Sunrisers Hyderabad,field,Y,Kolkata Knight Riders,SuperOver,NaN,NaN,LH Ferguson,"['Shubman Gill', 'RA Tripathi', 'N Rana', 'AD ...","['JM Bairstow', 'KS Williamson', 'PK Garg', 'D...",PG Pathak,S Ravi
159,1216517,NaN,2020-10-18,2020/21,36,Mumbai Indians,Kings XI Punjab,Dubai International Cricket Stadium,Mumbai Indians,bat,Y,Kings XI Punjab,SuperOver,NaN,NaN,KL Rahul,"['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...","['KL Rahul', 'MA Agarwal', 'CH Gayle', 'N Poor...",Nitin Menon,PR Reiffel
184,1216547,NaN,2020-09-28,2020/21,10,Royal Challengers Bangalore,Mumbai Indians,Dubai International Cricket Stadium,Mumbai Indians,field,Y,Royal Challengers Bangalore,SuperOver,NaN,NaN,AB de Villiers,"['D Padikkal', 'AJ Finch', 'V Kohli', 'AB de V...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...",Nitin Menon,PR Reiffel
192,1216493,NaN,2020-09-20,2020/21,2,Delhi Capitals,Kings XI Punjab,Dubai International Cricket Stadium,Kings XI Punjab,field,Y,Delhi Capitals,SuperOver,NaN,NaN,MP Stoinis,"['PP Shaw', 'S Dhawan', 'SO Hetmyer', 'SS Iyer...","['KL Rahul', 'MA Agarwal', 'KK Nair', 'N Poora...",AK Chaudhary,Nitin Menon
203,1178426,Mumbai,2019-05-02,2019,51,Mumbai Indians,Sunrisers Hyderabad,Wankhede Stadium,Mumbai Indians,bat,Y,Mumbai Indians,SuperOver,NaN,NaN,JJ Bumrah,"['RG Sharma', 'Q de Kock', 'SA Yadav', 'E Lewi...","['WP Saha', 'MJ Guptill', 'MK Pandey', 'KS Wil...",CK Nandan,S Ravi
244,1175365,Delhi,2019-03-30,2019,10,Kolkata Knight Riders,Delhi Capitals,Arun Jaitley Stadium,Delhi Capitals,field,Y,Delhi Capitals,SuperOver,NaN,NaN,PP Shaw,"['NS Naik', 'CA Lynn', 'RV Uthappa', 'N Rana',...","['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...",AY Dandekar,Nitin Menon
339,1082625,Rajkot,2017-04-29,2017,35,Gujarat Lions,Mumbai Indians,Saurashtra Cricket Association Stadium,Gujarat Lions,bat,Y,Mumbai Indians,SuperOver,NaN,NaN,KH Pandya,"['Ishan Kishan', 'BB McCullum', 'SK Raina', 'A...","['PA Patel', 'JC Buttler', 'N Rana', 'RG Sharm...",AK Chaudhary,CB Gaffaney
474,829741,Ahmedabad,2015-04-21,2015,18,Rajasthan Royals,Kings XI Punjab,"Sardar Patel Stadium, Motera",Kings XI Punjab,field,Y,Kings XI Punjab,SuperOver,NaN,NaN,SE Marsh,"['AM Rahane', 'SR Watson', 'DJ Hooda', 'SPD Sm...","['M Vijay', 'V Sehwag', 'SE Marsh', 'GJ Maxwel...",M Erasmus,S Ravi
533,729315,Abu Dhabi,2014-04-29,2014,19,Kolkata Knight Riders,Rajasthan Royals,Sheikh Zayed Stadium,Rajasthan Royals,bat,Y,Rajasthan Royals,SuperOver,NaN,NaN,JP Faulkner,"['G Gambhir', 'MS Bisla', 'JH Kallis', 'MK Pan...","['AM Rahane', 'KK Nair', 'SV Samson', 'SR Wats...",Aleem Dar,AK Chaudhary
608,598017,Bangalore,2013-04-16,2013,21,Royal Challengers Bangalore,Delhi Daredevils,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Y,Royal Challengers Bangalore,SuperOver,NaN,NaN,V Kohli,"['CH Gayle', 'KL Rahul', 'V Kohli', 'AB de Vil...","['DA Warner', 'V Sehwag', 'MC Juneja', 'DPMD J...",M Erasmus,VA Kulkarni
621,598004,Hyderabad,2013-04-07,2013,7,Sunrisers Hyderabad,Royal Challengers Bangalore,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bangalore,bat,Y,Sunrisers Hyderabad,SuperOver,NaN,NaN,GH Vihari,"['PA Reddy', 'PA Patel', 'CL White', 'GH Vihar...","['CH Gayle', 'TM Dilshan', 'V Kohli', 'KK Nair...",AK Chaudhary,S Ravi
819,419121,Chennai,2010-03-21,2009/10,16,Chennai Super Kings,Kings XI Punjab,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,field,Y,Kings XI Punjab,SuperOver,NaN,NaN,J Theron,"['PA Patel', 'ML Hayden', 'SK Raina', 'M Vijay...","['RS Bopara', 'IK Pathan', 'KC Sangakkara', 'D...",K Hariharan,DJ Harper
883,392190,Cape Town,2009-04-23,2009,10,Kolkata Knight Riders,Rajasthan Royals,Newlands,Kolkata Knight Riders,field,Y,Rajasthan Royals,SuperOver,NaN,NaN,YK Pathan,"['CH Gayle', 'BB McCullum', 'LR Shukla', 'BJ H...","['GC Smith', 'PC Valthaty', 'RJ Quiney', 'YK P...",MR Benson,M Erasmus

In [45]:
df[(df['WinningTeam'] == 'Chennai Super Kings') & (df['City'] == 'Kolkata')]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
224,1178404,Kolkata,2019-04-14,2019,29,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,5.0,NaN,Imran Tahir,"['CA Lynn', 'SP Narine', 'N Rana', 'RV Uthappa...","['SR Watson', 'F du Plessis', 'SK Raina', 'AT ...",CK Nandan,RJ Tucker
602,598022,Kolkata,2013-04-20,2013,26,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Kolkata Knight Riders,bat,N,Chennai Super Kings,Wickets,4.0,NaN,RA Jadeja,"['G Gambhir', 'YK Pathan', 'JH Kallis', 'EJG M...","['MEK Hussey', 'R Ashwin', 'M Vijay', 'SK Rain...",Asad Rauf,AK Chaudhary
641,548368,Kolkata,2012-05-14,2012,63,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,5.0,NaN,MEK Hussey,"['G Gambhir', 'BB McCullum', 'JH Kallis', 'MK ...","['MEK Hussey', 'M Vijay', 'SK Raina', 'F du Pl...",JD Cloete,SJA Taufel
827,419113,Kolkata,2010-03-16,2009/10,8,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Chennai Super Kings,bat,N,Chennai Super Kings,Runs,55.0,NaN,MS Dhoni,"['BJ Hodge', 'MK Tiwary', 'SC Ganguly', 'WP Sa...","['M Vijay', 'ML Hayden', 'SK Raina', 'S Badrin...",HDPK Dharmasena,AM Saheba
908,336025,Kolkata,2008-05-18,2007/08,41,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Kolkata Knight Riders,bat,N,Chennai Super Kings,Runs,3.0,D/L,M Ntini,"['Salman Butt', 'Mohammad Hafeez', 'SC Ganguly...","['PA Patel', 'SP Fleming', 'S Vidyut', 'SK Rai...",Asad Rauf,K Hariharan

In [46]:
df[(df['Player_of_Match'] == 'MS Dhoni') & ((df['Team1'] == 'Mumbai Indians')|(df['Team2'] == 'Mumbai Indians'))]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
630,548379,Bangalore,2012-05-23,2012,Elimination Final,Chennai Super Kings,Mumbai Indians,M Chinnaswamy Stadium,Mumbai Indians,field,N,Chennai Super Kings,Runs,38.0,NaN,MS Dhoni,"['M Vijay', 'MEK Hussey', 'SK Raina', 'S Badri...","['SR Tendulkar', 'DR Smith', 'RG Sharma', 'KD ...",BF Bowden,HDPK Dharmasena

In [50]:
df[(df['TossDecision'] == 'bat') & (df['TossWinner'] == 'Gujarat Titans') & (df['WinningTeam'] == 'Gujarat Titans')]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
17,1304103,Pune,2022-05-10,2022,57,Gujarat Titans,Lucknow Super Giants,"Maharashtra Cricket Association Stadium, Pune",Gujarat Titans,bat,N,Gujarat Titans,Runs,62.0,NaN,Shubman Gill,"['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...","['Q de Kock', 'KL Rahul', 'DJ Hooda', 'KS Shar...",KN Ananthapadmanabhan,MA Gough
39,1304081,Navi Mumbai,2022-04-23,2022,35,Gujarat Titans,Kolkata Knight Riders,"Dr DY Patil Sports Academy, Mumbai",Gujarat Titans,bat,N,Gujarat Titans,Runs,8.0,NaN,Rashid Khan,"['WP Saha', 'Shubman Gill', 'HH Pandya', 'DA M...","['SW Billings', 'SP Narine', 'SS Iyer', 'N Ran...",KN Ananthapadmanabhan,UV Gandhe

In [51]:
df[df['WinningTeam'] == 'Gujarat Titans']

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
12,1304108,Mumbai,2022-05-15,2022,62,Chennai Super Kings,Gujarat Titans,"Wankhede Stadium, Mumbai",Chennai Super Kings,bat,N,Gujarat Titans,Wickets,7.0,NaN,WP Saha,"['RD Gaikwad', 'DP Conway', 'MM Ali', 'N Jagad...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",R Pandit,VK Sharma
17,1304103,Pune,2022-05-10,2022,57,Gujarat Titans,Lucknow Super Giants,"Maharashtra Cricket Association Stadium, Pune",Gujarat Titans,bat,N,Gujarat Titans,Runs,62.0,NaN,Shubman Gill,"['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...","['Q de Kock', 'KL Rahul', 'DJ Hooda', 'KS Shar...",KN Ananthapadmanabhan,MA Gough
31,1304089,Mumbai,2022-04-30,2022,43,Royal Challengers Bangalore,Gujarat Titans,"Brabourne Stadium, Mumbai",Royal Challengers Bangalore,bat,N,Gujarat Titans,Wickets,6.0,NaN,R Tewatia,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['WP Saha', 'Shubman Gill', 'B Sai Sudharsan',...",HAS Khalid,VK Sharma
34,1304086,Mumbai,2022-04-27,2022,40,Sunrisers Hyderabad,Gujarat Titans,"Wankhede Stadium, Mumbai",Gujarat Titans,field,N,Gujarat Titans,Wickets,5.0,NaN,Umran Malik,"['Abhishek Sharma', 'KS Williamson', 'RA Tripa...","['WP Saha', 'Shubman Gill', 'HH Pandya', 'DA M...",CB Gaffaney,Navdeep Singh
39,1304081,Navi Mumbai,2022-04-23,2022,35,Gujarat Titans,Kolkata Knight Riders,"Dr DY Patil Sports Academy, Mumbai",Gujarat Titans,bat,N,Gujarat Titans,Runs,8.0,NaN,Rashid Khan,"['WP Saha', 'Shubman Gill', 'HH Pandya', 'DA M...","['SW Billings', 'SP Narine', 'SS Iyer', 'N Ran...",KN Ananthapadmanabhan,UV Gandhe
45,1304075,Pune,2022-04-17,2022,29,Chennai Super Kings,Gujarat Titans,"Maharashtra Cricket Association Stadium, Pune",Gujarat Titans,field,N,Gujarat Titans,Wickets,3.0,NaN,DA Miller,"['RD Gaikwad', 'RV Uthappa', 'MM Ali', 'AT Ray...","['WP Saha', 'Shubman Gill', 'V Shankar', 'A Ma...",KN Ananthapadmanabhan,UV Gandhe
50,1304070,Mumbai,2022-04-14,2022,24,Gujarat Titans,Rajasthan Royals,"Dr DY Patil Sports Academy, Mumbai",Rajasthan Royals,field,N,Gujarat Titans,Runs,37.0,NaN,HH Pandya,"['MS Wade', 'Shubman Gill', 'V Shankar', 'HH P...","['JC Buttler', 'D Padikkal', 'R Ashwin', 'SV S...",CB Gaffaney,R Pandit
58,1304062,Mumbai,2022-04-08,2022,16,Punjab Kings,Gujarat Titans,"Brabourne Stadium, Mumbai",Gujarat Titans,field,N,Gujarat Titans,Wickets,6.0,NaN,Shubman Gill,"['MA Agarwal', 'S Dhawan', 'JM Bairstow', 'LS ...","['MS Wade', 'Shubman Gill', 'B Sai Sudharsan',...",AK Chaudhary,VK Sharma
64,1304056,Pune,2022-04-02,2022,10,Gujarat Titans,Delhi Capitals,"Maharashtra Cricket Association Stadium, Pune",Delhi Capitals,field,N,Gujarat Titans,Runs,14.0,NaN,LH Ferguson,"['MS Wade', 'Shubman Gill', 'V Shankar', 'HH P...","['PP Shaw', 'TL Seifert', 'Mandeep Singh', 'RR...",KN Ananthapadmanabhan,UV Gandhe
70,1304050,Mumbai,2022-03-28,2022,4,Lucknow Super Giants,Gujarat Titans,"Wankhede Stadium, Mumbai",Gujarat Titans,field,N,Gujarat Titans,Wickets,5.0,NaN,Mohammed Shami,"['KL Rahul', 'Q de Kock', 'E Lewis', 'MK Pande...","['Shubman Gill', 'MS Wade', 'V Shankar', 'HH P...",PG Pathak,VK Sharma

34 Use the file spotify.csv

1. Convert this file into a pandas Data Frame. (0.5 marks)
2. Display basic c information like memory and data types for this data frame. (0.5 marks)
3. Display basic statistics like mean, std, quartiles, etc. for this data frame.(0.5 marks)
4. Create a correlation table for the data frame and comment about what kind of correlaƟon is there between danceability and energy (0.5
marks)
5. Display first five rows for this data frame.(0.5 marks)
6. Display last five rows for this data frame. (0.5 marks)
7. Display the rows between 15 to 39 for this data frame. (0.5 marks)
8. Display the data only for last five rows and last five columns for this data frame. (0.5 marks)
9. Display the shape for this data frame. (0.5 marks)
10. Display the sum of NULL values for all the columns. (0.5 marks)
11. Remove first 3 columns from this Data Frame. (0.5 marks)
12. Remove first 10 rows from this Data Frame. (0.5 marks)
13. After removing first 3 columns and first 10 rows from this data frame find outliers for the column popularity. (1 marks)
14. After removing first 3 columns and first 10 rows from this data frame remove outliers for the column energy then display the data frame.
(1 marks)
15. Display cross tabulaƟon between Ɵme_signature and track_genre for actual Data Frame. (1 marks)ta Frame. (1 marks)

In [54]:
url = "https://drive.google.com/file/d/1wkl0Z0FNe8nEjEsx3lBmO3vIg7pihk6i/view"
url='https://drive.google.com/uc?id=' + url.split('/')[-2]
df = pd.read_csv(url)
df.info() # basic info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  object
 2   artists           113999 non-null  object
 3   album_name        113999 non-null  object
 4   track_name        113999 non-null  object
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(6), object(5)
memory usage: 17.5+ MB

In [55]:
df.describe() # basic statistics

,Unnamed: 0,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,114000.000000,114000.000000,1.140000e+05,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,56999.500000,33.238535,2.280292e+05,0.566800,0.641383,5.309140,-8.258960,0.637553,0.084652,0.314910,0.156050,0.213553,0.474068,122.147837,3.904035
std,32909.109681,22.305078,1.072977e+05,0.173542,0.251529,3.559987,5.029337,0.480709,0.105732,0.332523,0.309555,0.190378,0.259261,29.978197,0.432621
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28499.750000,17.000000,1.740660e+05,0.456000,0.472000,2.000000,-10.013000,0.000000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218750,4.000000
50%,56999.500000,35.000000,2.129060e+05,0.580000,0.685000,5.000000,-7.004000,1.000000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000,4.000000
75%,85499.250000,50.000000,2.615060e+05,0.695000,0.854000,8.000000,-5.003000,1.000000,0.084500,0.598000,0.049000,0.273000,0.683000,140.071000,4.000000
max,113999.000000,100.000000,5.237295e+06,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

In [58]:
df.corr(numeric_only=True) # corr table
# Danceability and energy are positively correlated but it is not a good correlation as corr value is just 0.13

,Unnamed: 0,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
Unnamed: 0,1.000000,0.032142,-0.032743,-0.054736,0.003444,-0.055994,-0.005520,-0.027307,0.005107,-0.084952,0.076840,-0.070286,0.033639,0.053111,-0.025824,-0.021115
popularity,0.032142,1.000000,-0.007101,0.044082,0.035448,0.001056,-0.003853,0.050423,-0.013931,-0.044927,-0.025472,-0.095139,-0.005387,-0.040534,0.013205,0.031073
duration_ms,-0.032743,-0.007101,1.000000,-0.065263,-0.073426,0.058523,0.008114,-0.003470,-0.035556,-0.062600,-0.103788,0.124371,0.010321,-0.154479,0.024346,0.018225
explicit,-0.054736,0.044082,-0.065263,1.000000,0.122507,0.096955,0.004484,0.108588,-0.037212,0.307952,-0.094403,-0.103404,0.032549,-0.003381,-0.002816,0.038386
danceability,0.003444,0.035448,-0.073426,0.122507,1.000000,0.134325,0.036469,0.259077,-0.069219,0.108626,-0.171533,-0.185606,-0.131617,0.477341,-0.050450,0.207218
energy,-0.055994,0.001056,0.058523,0.096955,0.134325,1.000000,0.048006,0.761690,-0.078362,0.142509,-0.733906,-0.181879,0.184796,0.258934,0.247851,0.187126
key,-0.005520,-0.003853,0.008114,0.004484,0.036469,0.048006,1.000000,0.038590,-0.135916,0.020418,-0.040937,-0.006823,-0.001600,0.034103,0.010917,0.015065
loudness,-0.027307,0.050423,-0.003470,0.108588,0.259077,0.761690,0.038590,1.000000,-0.041764,0.060826,-0.589803,-0.433477,0.076899,0.279848,0.212446,0.191992
mode,0.005107,-0.013931,-0.035556,-0.037212,-0.069219,-0.078362,-0.135916,-0.041764,1.000000,-0.046532,0.095553,-0.049955,0.014012,0.021953,0.000566,-0.024092
speechiness,-0.084952,-0.044927,-0.062600,0.307952,0.108626,0.142509,0.020418,0.060826,-0.046532,1.000000,-0.002186,-0.089616,0.205219,0.036635,0.017273,-0.000011
acousticness,0.076840,-0.025472,-0.103788,-0.094403,-0.171533,-0.733906,-0.040937,-0.589803,0.095553,-0.002186,1.000000,0.104027,-0.020700,-0.107070,-0.208224,-0.176138
instrumentalness,-0.070286,-0.095139,0.124371,-0.103404,-0.185606,-0.181879,-0.006823,-0.433477,-0.049955,-0.089616,0.104027,1.000000,-0.079893,-0.324312,-0.050330,-0.082580
liveness,0.033639,-0.005387,0.010321,0.032549,-0.131617,0.184796,-0.001600,0.076899,0.014012,0.205219,-0.020700,-0.079893,1.000000,0.019086,0.000600,-0.023651
valence,0.053111,-0.040534,-0.154479,-0.003381,0.477341,0.258934,0.034103,0.279848,0.021953,0.036635,-0.107070,-0.324312,0.019086,1.000000,0.078273,0.133686
tempo,-0.025824,0.013205,0.024346,-0.002816,-0.050450,0.247851,0.010917,0.212446,0.000566,0.017273,-0.208224,-0.050330,0.000600,0.078273,1.000000,0.066641
time_signature,-0.021115,0.031073,0.018225,0.038386,0.207218,0.187126,0.015065,0.191992,-0.024092,-0.000011,-0.176138,-0.082580,-0.023651,0.133686,0.066641,1.000000

In [59]:
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [60]:
df.tail()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.235,...,-16.393,1,0.0422,0.640,0.928,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.117,...,-18.318,0,0.0401,0.994,0.976,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.329,...,-10.895,0,0.0420,0.867,0.000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.506,...,-10.889,1,0.0297,0.381,0.000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.487,...,-10.204,0,0.0725,0.681,0.000,0.0893,0.7080,79.198,4,world-music

In [68]:
df.loc[15:39]

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
15,15,1KHdq8NK9QxnGjdXb55NiG,Landon Pigg,The Boy Who Never,Falling in Love at a Coffee Shop,58,244986,False,0.489,0.5610,...,-7.933,1,0.0274,0.2000,0.000046,0.1790,0.2380,83.457,3,acoustic
16,16,6xKeQgzfjixSUld14qUezm,Andrew Foy;Renee Foy,ily (i love you baby),ily (i love you baby),56,129750,False,0.706,0.1120,...,-18.098,1,0.0391,0.8270,0.000004,0.1250,0.4140,110.154,4,acoustic
17,17,4Yo0igmcoNyat1secaH0OD,Andrew Foy;Renee Foy,At My Worst,At My Worst,54,169728,False,0.795,0.0841,...,-18.090,0,0.0461,0.7420,0.000012,0.0853,0.6090,91.803,4,acoustic
18,18,2qLMf6TuEC3ruGJg4SMMN6,Jason Mraz;Colbie Caillat,We Sing. We Dance. We Steal Things.,Lucky,68,189613,False,0.625,0.4140,...,-8.700,1,0.0369,0.2940,0.000000,0.1510,0.6690,130.088,4,acoustic
19,19,6CgNoAbFJ4Q4Id4EjtbXlC,Boyce Avenue;Bea Miller,"Cover Sessions, Vol. 4",Photograph,67,260186,False,0.717,0.3200,...,-8.393,1,0.0283,0.8300,0.000000,0.1070,0.3220,107.946,4,acoustic
20,20,3S0OXQeoh0w6AY8WQVckRW,Jason Mraz,We Sing. We Dance. We Steal Things.,I'm Yours,75,242946,False,0.703,0.4440,...,-9.331,1,0.0417,0.5590,0.000000,0.0973,0.7120,150.960,4,acoustic
21,21,210JCw2LbYD4YIs8GiZ9iP,Boyce Avenue;Jennel Garcia,"Cover Sessions, Vol. 3",Demons,63,174174,False,0.678,0.3510,...,-8.654,1,0.0266,0.7470,0.000000,0.3550,0.5690,90.032,4,acoustic
22,22,5TvE3pk05pyFIGdSY9j4DJ,A Great Big World;Christina Aguilera,Is There Anybody Out There? - Track by Track C...,Say Something,70,229400,False,0.407,0.1470,...,-8.822,1,0.0355,0.8570,0.000003,0.0913,0.0765,141.284,3,acoustic
23,23,0BUuuEvNa5T4lMaewyiudB,Jason Mraz,Coffee Moment,93 Million Miles,0,216386,False,0.572,0.4540,...,-10.286,1,0.0258,0.4770,0.000014,0.0974,0.5150,140.182,4,acoustic
24,24,3Hn3LfhrQOaKihdCibJsTs,Jason Mraz,Human - Best Adult Pop Tunes,Unlonely,0,231266,False,0.796,0.6670,...,-4.831,0,0.0392,0.3810,0.000000,0.2210,0.7540,97.988,4,acoustic
25,25,6D33wCKzWtNEgOovgeVJ7r,Jason Mraz,Mellow Adult Pop,Bella Luna,1,302346,False,0.755,0.4540,...,-9.609,0,0.0352,0.7570,0.000000,0.2360,0.3300,120.060,4,acoustic
26,26,5IfCZDRXZrqZSm8AwE44PG,Jason Mraz,Holly Jolly Christmas,Winter Wonderland,0,131760,False,0.620,0.3090,...,-9.209,1,0.0495,0.7880,0.000000,0.1460,0.6640,145.363,4,acoustic
27,27,0dzKBptH2P5j5a0MifBMwM,Jason Mraz,Feeling Good - Adult Pop Favorites,If It Kills Me,0,273653,False,0.633,0.4290,...,-6.784,0,0.0381,0.0444,0.000000,0.1320,0.5200,143.793,4,acoustic
28,28,5QAMZTM5cmLg3fHX9ZbTZi,Jason Mraz,Christmas Time,Winter Wonderland,0,131760,False,0.620,0.3090,...,-9.209,1,0.0495,0.7880,0.000000,0.1460,0.6640,145.363,4,acoustic
29,29,2qESE1ZeWly7I3YjyTXmXh,Jason Mraz,Perfect Christmas Hits,Winter Wonderland,0,131760,False,0.620,0.3090,...,-9.209,1,0.0495,0.7880,0.000000,0.1460,0.6640,145.363,4,acoustic
30,30,3EQV1ZHtHvq9OnVRYIdbg3,Jason Mraz,Merry Christmas,Winter Wonderland,0,131760,False,0.620,0.3090,...,-9.209,1,0.0495,0.7880,0.000000,0.1460,0.6640,145.363,4,acoustic
31,31,3ax0rfGb7exLtl02LL08U9,Jason Mraz,Christmas Music - Holiday Hits,Winter Wonderland,0,131760,False,0.620,0.3090,...,-9.209,1,0.0495,0.7880,0.000000,0.1460,0.6640,145.363,4,acoustic
32,32,1m5LC29RE52Bxy7hxvpOlL,Chord Overstreet,Christmas Country Songs 2022,All I Want For Christmas Is A Real Good Tan,0,234186,False,0.593,0.4550,...,-8.192,1,0.0388,0.3660,0.000000,0.0914,0.5640,202.019,4,acoustic
33,33,3H36x7buZdQD4687VmFrwY,Brandi Carlile;Sam Smith,Human - Best Adult Pop Tunes,Party of One,0,259558,False,0.296,0.2060,...,-11.799,1,0.0412,0.7820,0.000225,0.0959,0.2020,165.400,4,acoustic
34,34,0xbMRcMFqxJq1Wa7tvWPtn,Brandi Carlile;Sam Smith,Feeling Good - Adult Pop Favorites,Party of One,0,259558,False,0.296,0.2060,...,-11.799,1,0.0412,0.7820,0.000225,0.0959,0.2020,165.400,4,acoustic
35,35,6h061f44HZPj1OXO2nA45d,Brandi Carlile;Sam Smith,Mellow Bars R'n'B,Party of One,0,259558,False,0.296,0.2060,...,-11.799,1,0.0412,0.7820,0.000225,0.0959,0.2020,165.400,4,acoustic
36,36,62EwQLDw0dprDzuLwQ0sH1,KT Tunstall,Chill Christmas Dinner,Lonely This Christmas,0,257493,False,0.409,0.1530,...,-10.740,0,0.0306,0.9390,0.000026,0.1080,0.1800,85.262,4,acoustic
37,37,3lvo0I8c2qBJDLZWqExDgC,Brandi Carlile,rainy day indie,Throwing Good After Bad,0,247791,False,0.501,0.0952,...,-12.931,1,0.0540,0.9630,0.000016,0.0915,0.3160,138.016,4,acoustic
38,38,1ae8XfBQ3fDEvmBjFaemGV,Brandi Carlile,Coffee Moment,This Time Tomorrow,0,206267,False,0.606,0.3260,...,-10.031,1,0.0294,0.8410,0.000000,0.1390,0.4140,91.626,4,acoustic
39,39,0adVktNVJXPZfhQe6B1NO5,KT Tunstall,sadsadchristmas,Lonely This Christmas,0,257493,False,0.409,0.1530,...,-10.740,0,0.0306,0.9390,0.000026,0.1080,0.1800,85.262,4,acoustic

In [77]:
df.tail(5).iloc[:, -5:] # Display the data only for last five rows and last five columns for this data frame. (

        liveness  valence    tempo  time_signature  track_genre
113995    0.0863   0.0339  125.995               5  world-music
113996    0.1050   0.0350   85.239               4  world-music
113997    0.0839   0.7430  132.378               4  world-music
113998    0.2700   0.4130  135.960               4  world-music
113999    0.0893   0.7080   79.198               4  world-music

In [78]:
df.shape

(114000, 21)

In [82]:
df.isnull().sum() # Sum of null values

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [88]:
df.iloc[:,3:] # Removing first 3 cols

,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,5,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,0,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,0,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,Change Your World,Friends,41,283893,False,0.587,0.5060,7,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,1,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [89]:
df.iloc[10:] # Remove first 10 rows

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
10,10,4mzP5mHkRvGxdhdGdAH7EJ,Zack Tabudlo,Episode,Give Me Your Forever,74,244800,False,0.627,0.363,...,-8.127,1,0.0291,0.279,0.000000,0.0928,0.3010,99.905,4,acoustic
11,11,5ivF4eQBqJiVL5IAE9jRyl,Jason Mraz,Love Is a Four Letter Word,I Won't Give Up,69,240165,False,0.483,0.303,...,-10.058,1,0.0429,0.694,0.000000,0.1150,0.1390,133.406,3,acoustic
12,12,4ptDJbJl35d7gQfeNteBwp,Dan Berk,Solo,Solo,52,198712,False,0.489,0.314,...,-9.245,0,0.0331,0.749,0.000000,0.1130,0.6070,124.234,4,acoustic
13,13,0X9MxHR1rTkEHDjp95F2OO,Anna Hamilton,Bad Liar,Bad Liar,62,248448,False,0.691,0.234,...,-6.441,1,0.0285,0.777,0.000000,0.1200,0.2090,87.103,4,acoustic
14,14,4LbWtBkN82ZRhz9jqzgrb3,Chord Overstreet;Deepend,Hold On (Remix),Hold On - Remix,56,188133,False,0.755,0.780,...,-6.084,1,0.0327,0.124,0.000028,0.1210,0.3870,120.004,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.235,...,-16.393,1,0.0422,0.640,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.117,...,-18.318,0,0.0401,0.994,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.329,...,-10.895,0,0.0420,0.867,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.506,...,-10.889,1,0.0297,0.381,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.487,...,-10.204,0,0.0725,0.681,0.000000,0.0893,0.7080,79.198,4,world-music

In [133]:
# After removing first 3 columns and first 10 rows from this data frame find outliers for the column popularity.
df_pop = df.iloc[10:, 3:]
q1 = df_pop.popularity.quantile(0.25)
q3 = df_pop.popularity.quantile(0.75)
iqr = q3 - q1
lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr
outliers = df_pop.where((df_pop['popularity'] < lower) | (df_pop['popularity'] > upper))
outliers.popularity.count()

2

In [140]:
# After removing first 3 columns and first 10 rows from this data frame remove outliers for the column energy then display the data frame. 
df_energy = df.iloc[10:, 3:]
q1 = df_energy.energy.quantile(0.25)
q3 = df_energy.energy.quantile(0.75)
iqr = q3 - q1
lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr
np.where((df_energy['energy'] < lower) | (df_energy['energy'] > upper)) # There seems to be no outliers in energy column

(array([], dtype=int64),)

In [141]:
pd.crosstab(df.time_signature,df.track_genre)

track_genre,acoustic,afrobeat,alt-rock,alternative,ambient,anime,black-metal,bluegrass,blues,brazil,...,spanish,study,swedish,synth-pop,tango,techno,trance,trip-hop,turkish,world-music
time_signature,,,,,,,,,,,,,,,,,,,,,
0,0,0,1,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,3
1,9,5,1,2,39,7,20,5,6,5,...,2,6,6,2,17,3,5,7,3,7
3,101,52,56,64,264,63,129,80,97,42,...,55,49,49,16,167,26,37,38,75,132
4,877,930,940,922,648,923,838,909,894,939,...,937,934,928,981,784,969,949,951,909,844
5,13,13,2,12,46,7,13,6,3,14,...,6,11,17,1,32,2,9,4,12,14

35 Dataset link: https://drive.google.com/file/d/12RPDu4blghWiY02rsbnQnlkohBPjMmPo/view?usp=drive_link
1. Load the dataset into a pandas DataFrame (data_result.csv) and answer the following questions.
2. View the first few rows of the dataset
3. Check the shape of the dataset
4. View the first last rows of the dataset
5. Get summary statistics of numerical columns
6. Get summary statistics of numerical columns with 0.58 and 0.87 percentiles
7. Get summary statistics of all types of columns
8. Information of all columns
9. Check for missing values
10. Removing duplicates if duplicates
11. List out female students who have greater than 7 spi in all semesters.
12. Find number of students those who have greater than 8 spi in all 5 semesters

In [142]:
url = "https://drive.google.com/file/d/12RPDu4blghWiY02rsbnQnlkohBPjMmPo/view?usp=drive_link"
url = 'https://drive.google.com/uc?id=' + url.split('/')[-2]

df = pd.read_csv(url)
print("First few")
print(df.head())
print("Shape")
print(df.shape)
print("Last few")
print(df.tail())

First few
    1st   2nd   3rd   4th   5th  College Code  Gender  Roll no.  Subject Code
0  8.11  7.68  7.11  7.43  8.18           115  Female     17020            16
1  6.48  5.90  4.15  4.29  4.96           115    Male     17021            16
2  8.41  8.24  7.52  8.25  7.75           115  Female     17022            16
3  7.33  6.83  6.33  6.79  6.89           115    Male     17023            16
4  7.89  7.34  7.22  7.32  7.46           115    Male     17024            16
Shape
(46, 9)
Last few
     1st   2nd   3rd   4th   5th  College Code Gender  Roll no.  Subject Code
41  6.30  6.24  5.85  6.36  7.00           115   Male     17061            16
42  7.78  6.93  7.44  7.86  8.21           115   Male     17062            16
43  8.22  6.66  7.07  7.29  7.61           115   Male     17063            16
44  7.67  7.07  7.04  7.07  6.93           115   Male     17064            16
45  8.41  7.59  7.41  7.89  8.11           115   Male     17065            16

In [143]:
df.describe() # Statistical Analysis

,1st,2nd,3rd,4th,5th,College Code,Roll no.,Subject Code
count,46.000000,46.000000,46.000000,46.000000,46.000000,46.0,46.000000,46.0
mean,7.397609,6.930217,6.703043,7.237826,7.527609,115.0,17042.500000,16.0
std,0.798391,0.910425,0.917324,1.057981,0.967963,0.0,13.422618,0.0
min,5.670000,4.280000,4.150000,4.290000,4.860000,115.0,17020.000000,16.0
25%,6.787500,6.350000,6.217500,6.650000,6.890000,115.0,17031.250000,16.0
50%,7.440000,6.810000,7.000000,7.290000,7.625000,115.0,17042.500000,16.0
75%,8.040000,7.590000,7.322500,7.890000,8.210000,115.0,17053.750000,16.0
max,8.890000,8.720000,8.370000,9.250000,9.000000,115.0,17065.000000,16.0

In [145]:
df.describe(percentiles=[.25,0.58,0.87,.5,.75]) # Statistical Analysis with 0.58 and 0.87 percentile

,1st,2nd,3rd,4th,5th,College Code,Roll no.,Subject Code
count,46.000000,46.000000,46.000000,46.000000,46.000000,46.0,46.000000,46.0
mean,7.397609,6.930217,6.703043,7.237826,7.527609,115.0,17042.500000,16.0
std,0.798391,0.910425,0.917324,1.057981,0.967963,0.0,13.422618,0.0
min,5.670000,4.280000,4.150000,4.290000,4.860000,115.0,17020.000000,16.0
25%,6.787500,6.350000,6.217500,6.650000,6.890000,115.0,17031.250000,16.0
50%,7.440000,6.810000,7.000000,7.290000,7.625000,115.0,17042.500000,16.0
58%,7.787000,6.944000,7.114000,7.647000,7.860000,115.0,17046.100000,16.0
75%,8.040000,7.590000,7.322500,7.890000,8.210000,115.0,17053.750000,16.0
87%,8.220000,8.000000,7.530500,8.336500,8.531500,115.0,17059.150000,16.0
max,8.890000,8.720000,8.370000,9.250000,9.000000,115.0,17065.000000,16.0

In [147]:
df.describe(include='all') # ALl columns statistical analysis

,1st,2nd,3rd,4th,5th,College Code,Gender,Roll no.,Subject Code
count,46.000000,46.000000,46.000000,46.000000,46.000000,46.0,46,46.000000,46.0
unique,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,Male,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,38,NaN,NaN
mean,7.397609,6.930217,6.703043,7.237826,7.527609,115.0,NaN,17042.500000,16.0
std,0.798391,0.910425,0.917324,1.057981,0.967963,0.0,NaN,13.422618,0.0
min,5.670000,4.280000,4.150000,4.290000,4.860000,115.0,NaN,17020.000000,16.0
25%,6.787500,6.350000,6.217500,6.650000,6.890000,115.0,NaN,17031.250000,16.0
50%,7.440000,6.810000,7.000000,7.290000,7.625000,115.0,NaN,17042.500000,16.0
75%,8.040000,7.590000,7.322500,7.890000,8.210000,115.0,NaN,17053.750000,16.0
max,8.890000,8.720000,8.370000,9.250000,9.000000,115.0,NaN,17065.000000,16.0

In [148]:
df.info() # Info of all columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   1st           46 non-null     float64
 1   2nd           46 non-null     float64
 2   3rd           46 non-null     float64
 3   4th           46 non-null     float64
 4   5th           46 non-null     float64
 5   College Code  46 non-null     int64
 6   Gender        46 non-null     object
 7   Roll no.      46 non-null     int64
 8   Subject Code  46 non-null     int64
dtypes: float64(5), int64(3), object(1)
memory usage: 3.4+ KB

In [152]:
df.isna().sum() # Count of missing values in each column

1st             0
2nd             0
3rd             0
4th             0
5th             0
College Code    0
Gender          0
Roll no.        0
Subject Code    0
dtype: int64

In [154]:
df.drop_duplicates(inplace=True)

In [155]:
df

     1st   2nd   3rd   4th   5th  College Code  Gender  Roll no.  Subject Code
0   8.11  7.68  7.11  7.43  8.18           115  Female     17020            16
1   6.48  5.90  4.15  4.29  4.96           115    Male     17021            16
2   8.41  8.24  7.52  8.25  7.75           115  Female     17022            16
3   7.33  6.83  6.33  6.79  6.89           115    Male     17023            16
4   7.89  7.34  7.22  7.32  7.46           115    Male     17024            16
5   7.33  6.72  6.48  6.50  7.39           115    Male     17025            16
6   7.15  6.72  6.89  6.86  7.64           115    Male     17026            16
7   6.74  6.38  4.93  5.64  6.75           115    Male     17027            16
8   7.89  7.45  6.96  7.71  8.00           115  Female     17028            16
9   7.30  6.34  6.30  6.61  6.18           115    Male     17029            16
10  8.00  7.90  7.52  7.64  8.11           115    Male     17030            16
11  6.78  4.28  5.81  6.04  6.39           115    Male     17031            16
12  5.67  5.62  5.48  5.93  6.75           115    Male     17032            16
13  6.33  6.41  6.41  6.93  7.00           115    Male     17033            16
14  6.44  6.21  6.19  6.68  6.86           115    Male     17034            16
15  6.30  6.17  5.59  5.89  6.36           115    Male     17035            16
16  6.96  6.14  6.93  7.18  7.29           115    Male     17036            16
17  6.70  6.45  5.78  6.00  6.61           115    Male     17037            16
18  7.41  6.93  7.33  7.71  8.46           115    Male     17038            16
19  7.04  6.31  6.44  7.21  7.32           115    Male     17039            16
20  6.63  5.62  6.11  5.79  6.25           115    Male     17040            16
21  8.33  8.72  7.81  8.04  8.93           115  Female     17041            16
22  7.96  7.93  7.78  8.21  8.21           115    Male     17042            16
23  6.89  5.55  5.93  6.79  7.54           115    Male     17043            16
24  8.19  8.17  7.15  7.75  7.64           115    Male     17044            16
25  7.89  6.69  7.15  8.43  8.36           115  Female     17045            16
26  7.33  6.55  5.96  6.75  6.89           115    Male     17046            16
27  8.22  8.17  8.37  9.04  9.00           115    Male     17047            16
28  7.44  7.59  7.26  7.89  7.86           115    Male     17048            16
29  5.74  6.45  6.48  7.29  7.61           115    Male     17049            16
30  6.81  6.79  6.30  7.14  7.86           115  Female     17050            16
31  8.89  8.31  7.30  9.25  8.50           115  Female     17051            16
32  8.04  7.59  7.22  8.32  8.82           115    Male     17052            16
33  8.30  8.38  7.63  7.93  8.75           115    Male     17053            16
34  8.04  6.69  6.37  6.64  6.64           115    Male     17054            16
35  7.44  7.97  7.78  8.64  8.71           115    Male     17055            16
36  7.85  6.90  7.04  7.82  8.39           115  Female     17056            16
37  8.07  7.34  7.59  7.89  8.14           115    Male     17057            16
38  7.59  7.38  7.30  8.64  8.21           115    Male     17058            16
39  8.19  7.66  7.48  8.68  8.89           115    Male     17059            16
40  5.81  5.83  4.15  4.93  4.86           115    Male     17060            16
41  6.30  6.24  5.85  6.36  7.00           115    Male     17061            16
42  7.78  6.93  7.44  7.86  8.21           115    Male     17062            16
43  8.22  6.66  7.07  7.29  7.61           115    Male     17063            16
44  7.67  7.07  7.04  7.07  6.93           115    Male     17064            16
45  8.41  7.59  7.41  7.89  8.11           115    Male     17065            16

In [167]:
df['average'] = df.iloc[:,:5].sum(axis=1)/5

In [170]:
df[(df['Gender'] == 'Female') & (df['average'] > 7)]

,1st,2nd,3rd,4th,5th,College Code,Gender,Roll no.,Subject Code,average
0,8.11,7.68,7.11,7.43,8.18,115,Female,17020,16,7.702
2,8.41,8.24,7.52,8.25,7.75,115,Female,17022,16,8.034
8,7.89,7.45,6.96,7.71,8.00,115,Female,17028,16,7.602
21,8.33,8.72,7.81,8.04,8.93,115,Female,17041,16,8.366
25,7.89,6.69,7.15,8.43,8.36,115,Female,17045,16,7.704
31,8.89,8.31,7.30,9.25,8.50,115,Female,17051,16,8.450
36,7.85,6.90,7.04,7.82,8.39,115,Female,17056,16,7.600

In [171]:
df[(df['average'] > 8)]

,1st,2nd,3rd,4th,5th,College Code,Gender,Roll no.,Subject Code,average
2,8.41,8.24,7.52,8.25,7.75,115,Female,17022,16,8.034
21,8.33,8.72,7.81,8.04,8.93,115,Female,17041,16,8.366
22,7.96,7.93,7.78,8.21,8.21,115,Male,17042,16,8.018
27,8.22,8.17,8.37,9.04,9.00,115,Male,17047,16,8.560
31,8.89,8.31,7.30,9.25,8.50,115,Female,17051,16,8.450
33,8.30,8.38,7.63,7.93,8.75,115,Male,17053,16,8.198
35,7.44,7.97,7.78,8.64,8.71,115,Male,17055,16,8.108
39,8.19,7.66,7.48,8.68,8.89,115,Male,17059,16,8.180

36 https://drive.google.com/file/d/1jeuTUVJibNBcQlAyzgLo7XazqXC58cnA/view?usp=drive_link

Use the file movies.csv which contains 1629 rows and 18 columns. Read this csv file and display the basic information like memory and data
types for this data frame.
Write python code for the following case
s: 
1.List out Movies Released in Year 2019. 
2.How Many Movies are having IMDti RaƟng > 7 (Display Number of Movies) .
3.List out the Movies wtith ‘Ɵtle’ and ‘story’ whose IMDB Votes > 2000 0.
4.List out Movies Released in Year 2018, Display only Movie Title with Release Date of Year 2018 Movi es.
5.Display only Movie Title with its Wikipedia Link.

In [176]:
url = 'https://drive.google.com/file/d/1jeuTUVJibNBcQlAyzgLo7XazqXC58cnA/view?usp=drive_link'
url = 'https://drive.google.com/uc?id=' + url.split('/')[-2]

df = pd.read_csv(url)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

In [177]:
df[df['year_of_release'] == 2019] # Movies released in 2019

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
6,Fraud Saiyaan,tt5013008,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Fraud_Saiyaan,Fraud Saiyaan,Fraud Saiyyan,0,2019,109,Comedy|Drama,4.2,504,Fraud Saiyyan is the story of a con artist in ...,Fraud Saiyyan is the story of a con artist in ...,NaN,Arshad Warsi|Saurabh Shukla|Flora Saini|Sara L...,NaN,18 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,Commando 3 (film),tt8983168,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Commando_3_(film),Commando 3,Commando 3,0,2019,133,Action|Thriller,5.7,2400,A mysterious man is on an impending mission to...,Commando 3 is a Hindi movie starring Vidyut Ja...,NaN,Vidyut Jammwal|Adah Sharma|Angira Dhar|Sumeet ...,NaN,NaN
77,Mardaani 2,tt5668770,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mardaani_2,Mardaani 2,Mardaani 2,0,2019,103,Action|Drama|Thriller,7.4,8100,Shivani Shivaji Roy locks horns with the devil...,Shivani Shivaji Roy locks horns with the devil...,NaN,Rani Mukerji|Rajesh Sharma|Shruti Bapna|,NaN,NaN
78,Dabangg 3,tt7059844,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dabangg_3,Dabangg 3,Dabangg 3,0,2019,160,Action,3.0,15000,Third installment of the Dabanng film series.,Third installment of the Dabanng film series.,NaN,Salman Khan|Sonakshi Sinha|Sudeep|Mahesh Manjr...,NaN,NaN
79,Good Newwz,tt8504014,NaN,https://en.wikipedia.org/wiki/Good_Newwz,Good Newwz,Good Newwz,0,2019,134,Comedy|Drama|Romance,6.9,16000,It is an upcoming Indian romantic comedy film ...,It is an upcoming Indian romantic comedy film ...,NaN,Akshay Kumar|Kareena Kapoor|Kiara Advani|Tisca...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)

In [179]:
df[df['imdb_rating'] > 7].shape[0] # Movies having IMDB rating > 7

331

In [185]:
df[df['imdb_votes'] > 2000][['title_y', 'story']]

,title_y,story
0,Uri: The Surgical Strike,Divided over five chapters the film chronicle...
2,The Accidental Prime Minister,Based on the memoir by Indian policy analyst S...
8,Manikarnika: The Queen of Jhansi,Manikarnika born in Varanasi when Dixt a minis...
9,Thackeray,Balasaheb Thackrey works as a cartoonist for a...
11,Gully Boy,"Gully Boy is a film about a 22-year-old boy ""M..."
...,...,...
1607,Nayak: The Real Hero,Employed as a camera-man at a popular televisi...
1608,One 2 Ka 4,Javed Abbas (Jackie Shroff) is a widowed polic...
1616,Rehnaa Hai Terre Dil Mein,Madhav (Maddy) has love at first site with Ree...
1621,Tum Bin...: Love Will Find a Way,Shekar and Amar meet at a party where Amar ask...
1628,Humsafar,Sara and Ashar are childhood friends who share...

In [187]:
df[df['year_of_release'] == 2018][['title_y']]

                        title_y
4               Evening Shadows
5                          Soni
16      Mard Ko Dard Nahin Hota
17                        Hamid
20    Mere Pyare Prime Minister
...                         ...
156                Rajma Chawal
157                        Zero
158                      Simmba
166          Thugs of Hindostan
1626            Sabse Bada Sukh

[79 rows x 1 columns]

In [189]:
df[['title_y', 'wiki_link']]

,title_y,wiki_link
0,Uri: The Surgical Strike,https://en.wikipedia.org/wiki/Uri:_The_Surgica...
1,Battalion 609,https://en.wikipedia.org/wiki/Battalion_609
2,The Accidental Prime Minister,https://en.wikipedia.org/wiki/The_Accidental_P...
3,Why Cheat India,https://en.wikipedia.org/wiki/Why_Cheat_India
4,Evening Shadows,https://en.wikipedia.org/wiki/Evening_Shadows
...,...,...
1624,Tera Mera Saath Rahen,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...
1625,Yeh Zindagi Ka Safar,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...
1626,Sabse Bada Sukh,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh
1627,Daaka,https://en.wikipedia.org/wiki/Daaka
1628,Humsafar,https://en.wikipedia.org/wiki/Humsafar